#!/bin/bash
# Copies the specified lexer to pygments-main/lexers/ and runs pygmentize on a file located inside examples/.
# Paths are hard-coded for a Pygments installation on either OSX 10.10 (via pip) or Arch Linux (via pacman).

# Usage:
# ./updateLexer elm.py

pygmentsDir=site-packages/pygments/lexers

if [[ $(uname) = "Darwin" ]]; then
    sudo cp "$*" /Library/Python/2.7/"$pygmentsDir"/"$*"
else
    sudo cp "$*" /usr/lib/python2.7/"$pygmentsDir"/"$*"
fi

pygmentize -f html -O full -o output/test.html examples/example.elm
