#!/bin/bash
# specify a lexer to test, e.g. ./updateLexer j.py
pygmentsDir=site-packages/pygments/lexers
if [[ $(uname) = "Darwin" ]]; then
    sudo cp "$*" /Library/Python/2.7/"$pygmentsDir"/j.py
else
    sudo cp "$*" /usr/lib/python2.7/"$pygmentsDir"/j.py
fi
#pygmentize -f html -O full -o output/test.html examples/testing.ijs
pygmentize -f html -O full -o output/test.html examples/pacman.ijs
