#!/bin/bash
# Copies the specified lexer to pygments-main/lexers/ and runs pygmentize on an example file.

# Usage:
# ./updateLexer elm.py

# on Arch Linux:
# /usr/lib/python2.7/site-packages/pygments/lexers
pygmentsDir=site-packages/pygments/lexers
if [[ $(uname) = "Darwin" ]]; then
    sudo cp "$*" /Library/Python/2.7/"$pygmentsDir"/"$*"
else
    sudo cp "$*" /usr/lib/python2.7/"$pygmentsDir"/"$*"
fi

# Be good and only put one thing in this directory.
pygmentize -f html -O full -o output/test.html examples/*
